image: node:10.6.0

stages:
 - build
 - test
 - deploy
before_script:

       - npm install
      
build-min-code:
 stage: build
 script:
  - ng build
 tags:
  - Development
 only:
  - CGXAngularWeb-Dev
